name: Docker Build and Push
on: [push, pull_request]
branches:
  - main
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            my-wallets-nextjs:${{ github.sha }}
            my-wallets-nextjs:latest
          cache-from: type=registry,ref=my-wallets-nextjs:cache
          cache-to: type=registry,ref=my-wallets-nextjs:cache,mode=max
          build-args: |
            NODE_ENV=production
            # Add any other build arguments here
